[project]
name = "nsfcoa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.4",
    "scholarversary>=0.1.0",
    "uvicorn>=0.32.0",
]
